#!/bin/sh

#TODO: setup variables to be external from this script and pulled in
thisdirectory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #gets the directory of the install file no matter where it's called from
repopath="$thisdirectory/../../" #takes us out of hooks and out of .git folder to the repo base
cd $repopath #go to repobase
repopath=$(pwd) #set repo base again
source "$repopath/dbsync/config.sh" #let's grab the config variables

#put the files into the database from the dump
"$repopath/dbsync/$dbname.sql" > "$mysqlpath/mysql" -u $mysqluser -p $mysqlpass $dbname