#!/bin/sh

#TODO: setup variables to be external from this script and pulled in
thisdirectory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #gets the directory of the install file no matter where it's called from
repopath="$thisdirectory/../../" #takes us out of hooks and out of .git folder back to the repo base
source "$repopath/dbsync/config.sh" #let's grab the config variables

[[ $mysqlpath = "" ]] && importcommand="mysql" || importcommand="$mysqlpath/mysql" #if path isn't specified assume mysql is a global command

echo "running command $importcommand"

#put the files into the database from the dump
"$repopath/dbsync/$dbname.sql" > "$importcommand" -u $mysqluser -p $mysqlpass $dbname